layout: "main"
logger: "console"
appname: "SPID Test"
template: "template_toolkit"
session: "Simple"

# Configuration for the Dancer::Plugin::SPID module:
plugins:
  SPID:
    sp_entityid: "https://www.prova.it/"
    sp_key_file: "sp.key"
    sp_cert_file: "sp.pem"
    sp_assertionconsumerservice:
      - "http://localhost:3000/spid-sso"
    sp_singlelogoutservice:
      "http://localhost:3000/spid-slo": "HTTP-Redirect"
    idp_metadata_dir: "idp_metadata/"
    login_endpoint: "/spid-login"
    logout_endpoint: "/spid-logout"
    sso_endpoint: "/spid-sso"
    slo_endpoint: "/spid-slo"
    metadata_endpoint: "/spid-metadata.xml"
